<?php
/**
 * @package        Nooku_Server
 * @subpackage     Comments
 * @copyright      Copyright (C) 2009 - 2012 Timble CVBA and Contributors. (http://www.timble.net)
 * @license        GNU GPLv3 <http://www.gnu.org/licenses/gpl.html>
 * @link           http://www.nooku.org
 */

use Nooku\Library;

/**
 * Comment Controller Permission Class
 *
 * @author     Terry Visser <http://nooku.assembla.com/profile/terryvisser>
 * @package    Nooku_Server
 * @subpackage Comments
 */
class CommentsControllerPermissionComment extends ApplicationControllerPermissionDefault
{

    /**
     * @return bool
     */
    public function canRender()
    {
        $comments = $this->getModel()->getRowset();
        foreach ($comments as $comment){

            if(!$this->getUser()->isAuthentic()){

                $comment->editable = false;
                $comment->deleteable = false;

            }elseif( $comment->created_by == $this->getUser()->getId()){

                //If the user is the owner of a comment he can edit or delete it.
                $comment->editable = true;
                $comment->deleteable = true;
            }elseif($this->getUser()->getRole() > 25){

                //If the user is Super Administrator he should be able to delete / edit it..
                $comment->editable = true;
                $comment->deleteable = true;
            }else{
                //Everything else should not be able to edit/delete
                $comment->editable = false;
                $comment->deleteable = false;
            }
        }
        return parent::canRender();

    }

    public function canEdit()
    {
        $comment = $this->getModel()->getRow();
        $result = false;

        if($this->getUser()->getRole() == 25){

            //If the user is Super Administrator he should be able to delete / edit it..
            $result = true;
        }elseif($comment->created_by == $this->getUser()->getId()){
            //If the user is the owner of a comment he can edit or delete it.
            $result = true;

        }
        return $result;
    }

    public function canAdd()
    {

        return parent::canAdd(); // TODO: Change the autogenerated stub
    }

    public function canDelete()
    {
        $comment = $this->getModel()->getRow();
        $result = false;
        if($comment->created_by == $this->getUser()->getId()){
            //If the user is the owner of a comment he can edit or delete it.
            $result = true;

        }elseif($this->getUser()->getRole() > 25){

            //If the user is Super Administrator he should be able to delete / edit it..
            //$comment->deleteable = true;
            //@todo deleteable must be on;
        }
        return $result;
    }


}